### ISSUE TITLE
Support for Hashing a payment 

### ISSUE THREAD

**Issue by rferguson10** [bambora-na/beanstream-php#23]
Is there a way to satisfy this new requirement?

**HASH KEY VALIDATION AUTHENTICATION** 

Effective September 30, 2018, TD Merchant Solutions will enable Hash Key Validation authentication on your Online Mart Account, to help protect you against fraudulent activity. This will ensure your payment transactions are authenticated before being posted to your Online Mart Account for processing. To ensure there is no impact to your transaction processing, you must update your integration to include a Hash value (where applicable) or another available API authentication method. 

Important: Effective September 30, 2018, if your integration is not updated payment transactions processed on your Online Mart Account may fail. 
 
Action Required

Contact your website or shopping cart provider to have them implement and deploy the required changes to support Hash Key Validation authentication. These changes must be completed prior to September 30, 2018 to ensure that your payment processing is not impacted. 
 
For instructions on how to secure your API through Hash Key Validation or another API authentication method, visit the support page of our support partner Bambora. Thank you for choosing TD Merchant Solutions for your e-commerce processing business.If you have any questions about these changes, contact Bambora by telephone at 1-888-472-0811, by online submission form or email at support@onlinemart.ca. 

https://help.na.bambora.com/hc/en-us/articles/360001544468-Authentication-Landing-Page

https://help.na.bambora.com/hc/en-us/articles/360001540547-Hashing-a-Payment-String

**Comment by ksaliba-bam** [comment]
Hello @rferguson10, 

The PHP SDK is integrated with the REST API, which utilizes authentication via an Authorization HTTP header and the 'Passcode' configured within the Order Settings of the account. The REST API does not allow for authentication based on hash key validation.

**Comment by ihsw** [comment]
@ksaliba-bam what does this mean for users of the PHP SDK? Will there need to be code changes to support hash key validation?

**Comment by ihsw** [comment]
@svenresch Thank you for clarifying, yes we are already using API token-based authentication.
